### ISSUE TITLE
Does not work in Vietnam because `Asia/Saigon` is missing

### ISSUE THREAD

**Issue by BenJackGill** [cccccroge/tz-geo-currency#1]
Love the idea behind this, but I found a bug.

I'm in Vietnam and `getCountry()` does not work.

This is because my timezone returns as `Asia/Saigon` and your [parsedZone1970](https://github.com/cccccroge/tz-geo-currency/blob/main/src/data/parsedZone1970.js) file only has `Asia/Ho_Chi_Minh` listed under the `VN` (Vietnam) country code.

I suggest adding both `Asia/Saigon` and `Asia/Ho_Chi_Minh` under the `VN` country code since it seems both are used for the same city, even though Ho Chi Minh is now the offical and correct name.

For proof, here is screenshot showing the returned timezone using `console.log(Intl.DateTimeFormat().resolvedOptions().timeZone)`:

![Screenshot 2024-06-25 at 2 54 23 PM](https://github.com/cccccroge/tz-geo-currency/assets/2043257/7adf53f0-ae39-497e-a38c-efd5600b3927)

**Comment by cccccroge** [comment]
Thank you for the feedback. I will study further for the related issues, it seems the IANA dataset is not up-to-date. If this is the case, then manually modifying the data file is not recommended as it might has more similar cases which require too much effort.

ref: https://github.com/tc39/proposal-temporal/issues/2509

**Comment by cccccroge** [comment]
@BenJackGill 
I found the actual problem: Browsers are using Unicode CLDR which is not exactly same as IANA dataset. 🤔
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions#timezone

From the MDN documentation, it seems IANA dataset is most up-to-date while Unicode CLDR keep deprecated cases for compatibility reasons.

So for the usage of this package, I think it's probably better to keep it align with Unicode CLDR. Now the only remaining problem is find the mapping from CLDR's timeZone to country code, which require additional study. I'll create a fixing PR after that. 🙏

**Comment by cccccroge** [comment]
I turns out Unicode CLDR doesn't have a mapping from timeZone to country alpha2 (I search the [cldr json repo](https://github.com/unicode-org/cldr-json) and does not find any alpha2 string that links back to timeZone) which makes it impossible to use CLDR's timezone data.

The easiest way to fix it is to use "backward" data from IANA Timezone dataset. You can check `Asia/Saigon` is marked as a deprecated name of `Asia/Ho_Chi_Minh`.
https://github.com/eggert/tz/blob/812aff32b32c02266361d5538351e0db2a1aee5b/backward#L319

So I'll make a fix based on this file. Though I don't know how reliable is the file for each browser implemenation (i.e. I do not know whether this cover all time zones that browser might use 😅)

**Comment by cccccroge** [comment]
@BenJackGill
It should work in Vietnam now.
https://github.com/cccccroge/tz-geo-currency/releases/tag/v1.0.5
